const product = [
    {
        "id": 1,
        "producto": "Agenda",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 2,
        "producto": "Agenda Perpetua",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 3,
        "producto": "Almohadon blanco",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 4,
        "producto": "Anotador chico",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 5,
        "producto": "Anotador mediano",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 6,
        "producto": "Azucarera - yerbera blanca",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 7,
        "producto": "Babero blanco",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 8,
        "producto": "bandeja desayuno madera",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 9,
        "producto": "Body bebe blanco",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 10,
        "producto": "Body bebe color",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 11,
        "producto": "Body bebe gris",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 12,
        "producto": "Box emprendedor",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 13,
        "producto": "Cantimplora kids",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 14,
        "producto": "Chop ceramica",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 15,
        "producto": "Combo jardin",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 16,
        "producto": "Cuaderno A4",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 17,
        "producto": "Cuaderno rivadavia",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 18,
        "producto": "Cuchara platica",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 19,
        "producto": "Gorra trucker color adulto",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 20,
        "producto": "Gorra trucker negra adulto",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 21,
        "producto": "Gorra trucker color niño",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 22,
        "producto": "Gorra trucker negra niño",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 23,
        "producto": "Jarro termico con tapa",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 24,
        "producto": "Llavero formas de madera",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 25,
        "producto": "Mate cerámica",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 26,
        "producto": "Mate listo",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 27,
        "producto": "Mate propileno",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 28,
        "producto": "Mousepad blanco",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 29,
        "producto": "Porta cel madera",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 30,
        "producto": "Porta vaso madera",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 31,
        "producto": "Remera algodon color niño",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 32,
        "producto": "Remera algodon niño",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 33,
        "producto": "Remera blanca spum",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 34,
        "producto": "Remera color algodón ",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 35,
        "producto": "Remera color algodón te ",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 36,
        "producto": "Remera gris spun",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 37,
        "producto": "Remera gris spun niño",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 38,
        "producto": "Remera gris spum te",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 39,
        "producto": "Remera gris spum ",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 40,
        "producto": "Remera gris spum niño",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 41,
        "producto": "Remera gris spum te",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 42,
        "producto": "Remera spum blanca niño",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 43,
        "producto": "Remera blanca spum",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 44,
        "producto": "Rompecabeza madera",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 45,
        "producto": "Set jardin blanco",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 46,
        "producto": "Set jardin color",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 46,
        "producto": "Taza cerámica",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 47,
        "producto": "Tenedor poly",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 48,
        "producto": "Toalla chica blanca",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 49,
        "producto": "Vaso de cafe con tapa poly",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 50,
        "producto": "Vaso Starbucks",
        "img": "",
        "descripcion": "",
    },
    {
        "id": 51,
        "producto": "Vinilo termosublimable ",
        "img": "",
        "descripcion": "",
    },
]
export default product